name: task
description: task.
publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
   

  ##### ------------------------ UI -------------------------- #####
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  
  lottie: ^1.4.3
  
  cached_network_image: ^3.2.3
  
  dropdown_button2: ^2.3.9

 
  intl: ^0.18.0
 
  file_picker: ^5.2.5
  flutter_screenutil: ^5.5.4
 
  url_launcher: ^6.1.14
  
  

  ##### ----------------------- Network ------------------------ #####
  dio: ^4.0.6
 


 

# ---- Dev ---- #
dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  # Linters
  flutter_lints: ^2.0.3
  lints: ^2.1.1
  dart_code_metrics_presets: ^2.4.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/task_app_icon.png"
  remove_alpha_ios: true


flutter_gen:
  output: lib/core/assets
  integrations:
    flutter_svg: true

# ---- Assets ---- #
flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - assets/icons/
  #   - assets/fonts/
  #   - assets/fonts/sf/
  #   - assets/videos/
  #   - assets/animation/
  #   - assets/lang/

  fonts:
    - family: SFArabic
      fonts:
        - asset: assets/fonts/sf/SF-Arabic.ttf
    - family: SFCompact
      fonts:
        - asset: assets/fonts/sf/SF-Compact-Text-Thin.ttf
          weight: 300
        - asset: assets/fonts/sf/SF-Compact-Text-Regular.ttf
          weight: 400
        - asset: assets/fonts/sf/SF-Compact-Text-Medium.ttf
          weight: 500
        - asset: assets/fonts/sf/SF-Compact-Text-Bold.ttf
          weight: 700